package za.co.gpbrij.cph.service;
import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import za.co.gpbrij.cph.api.*; import za.co.gpbrij.cph.domain.*; import za.co.gpbrij.cph.repository.*; import java.util.*;
@Service @Transactional public class PaymentService {
 private final PaymentRepository payments; private final CustomerRepository customers; private final BeneficiaryRepository beneficiaries; private final ApprovalRepository approvals; private final AuditLogRepository audits; private final SanctionEntryRepository sanctions;
 public PaymentService(PaymentRepository p,CustomerRepository c,BeneficiaryRepository b,ApprovalRepository a,AuditLogRepository l,SanctionEntryRepository s){payments=p;customers=c;beneficiaries=b;approvals=a;audits=l;sanctions=s;}
 public PaymentView create(CreatePaymentRequest r,String actor){var p=new Payment();p.setCustomer(customers.findById(r.customerId()).orElseThrow(()->new NotFoundException("Customer not found")));p.setBeneficiary(beneficiaries.findById(r.beneficiaryId()).orElseThrow(()->new NotFoundException("Beneficiary not found")));p.setAmount(r.amount());p.setCurrency(r.currency());p.setClientReference(r.clientReference());p.setValueDate(r.valueDate());p=payments.save(p);audit(p,"CREATED",actor,"Draft payment created");return PaymentView.from(p);}
 public PaymentView submit(String id,String actor){var p=get(id);require(p,PaymentStatus.DRAFT);p.setStatus(PaymentStatus.PENDING_APPROVAL);audit(p,"SUBMITTED",actor,"Payment submitted for maker-checker approval");return PaymentView.from(p);}
 public PaymentView decide(String id,DecisionRequest r){var p=get(id);require(p,PaymentStatus.PENDING_APPROVAL);var a=new Approval();a.setPayment(p);a.setApprover(r.actor());a.setDecision(r.decision().toUpperCase());a.setComments(r.comments());approvals.save(a);if("APPROVE".equalsIgnoreCase(r.decision())){p.setStatus(PaymentStatus.COMPLIANCE_REVIEW);screen(p,r.actor());}else if("REJECT".equalsIgnoreCase(r.decision())){p.setStatus(PaymentStatus.REJECTED);p.setRejectionReason(r.comments());}else throw new IllegalArgumentException("Decision must be APPROVE or REJECT");audit(p,"DECISION_"+r.decision().toUpperCase(),r.actor(),Objects.toString(r.comments(),""));return PaymentView.from(p);}
 private void screen(Payment p,String actor){boolean hit=sanctions.findAll().stream().filter(SanctionEntry::isActive).anyMatch(s->(s.getCountryCode()!=null&&s.getCountryCode().equalsIgnoreCase(p.getBeneficiary().getCountryCode()))||(s.getEntityName()!=null&&s.getEntityName().equalsIgnoreCase(p.getBeneficiary().getName())));if(hit){p.setStatus(PaymentStatus.REJECTED);p.setRejectionReason("Mock sanctions screening match");audit(p,"SANCTIONS_HIT",actor,"Beneficiary matched mock sanctions data");}else{p.setStatus(PaymentStatus.QUEUED);audit(p,"SANCTIONS_CLEAR",actor,"No mock sanctions match");}}
 public PaymentView process(String id,String actor){var p=get(id);require(p,PaymentStatus.QUEUED);p.setStatus(PaymentStatus.PROCESSING);p.setStatus(PaymentStatus.SETTLED);audit(p,"SETTLED",actor,"Mock gateway settlement completed");return PaymentView.from(p);}
 @Transactional(readOnly=true) public List<PaymentView> all(){return payments.findAll().stream().map(PaymentView::from).toList();} @Transactional(readOnly=true) public PaymentView one(String id){return PaymentView.from(get(id));}
 private Payment get(String id){return payments.findById(id).orElseThrow(()->new NotFoundException("Payment not found"));} private void require(Payment p,PaymentStatus s){if(p.getStatus()!=s)throw new IllegalStateException("Expected "+s+" but was "+p.getStatus());}
 private void audit(Payment p,String action,String actor,String detail){var a=new AuditLog();a.setEntityType("PAYMENT");a.setEntityId(p.getId());a.setAction(action);a.setActor(actor);a.setDetail(detail);audits.save(a);}
}
